### ISSUE TITLE
single profile display

### ISSUE THREAD

**Issue by Freddielah** [surveycto/conjoint#4]
Hi, iMofya, I tested this and it worked perfectly (!!)

I have two questions:
1. I want to only display one profile and ask a follow-up yes/no question instead of "which profile do you prefer" 
2. I'm curious as to why the unique-id element is needed? It says it's for the reshape in Stata, but the data will already have a uID generated in the cleaning process using respondents' phone numbers. Can I bypass this element?

**Comment by mofya1** [comment]
Hi @Freddielah, 

Thanks for engaging with us. Here are my responses: 

> I want to only display one profile and ask a follow-up yes/no question instead of "which profile do you prefer"

Unfortunately this is not possible. For now the the field plug-in displays two profiles all the time. If you prefer to display only one profile, you can do this without the field plug-in using [HTML tables](https://www.w3schools.com/html/html_tables.asp) and [randomization](https://docs.surveycto.com/02-designing-forms/03-advanced-topics/01.randomizing.html). You can always [submit a support request](https://support.surveycto.com/hc/en-us/requests/new) and we can guide you further. 

> I'm curious as to why the unique-id element is needed? It says it's for the reshape in Stata, but the data will already have a uID generated in the cleaning process using respondents' phone numbers. Can I bypass this element?

You can definitely skip that if is not needed. The sample is meant to provide guidance on how the field plug-in can be used, so you can feel free to add/remove parts depending on your workflow.

**Comment by Freddielah** [comment]
Awesome, thanks again, Mofya
